## 开发环境
server:
  port: 9048

spring:
  #  autoconfigure:
  #    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbkpoec225c821d8vo.mysql.zhangbei.rds.aliyuncs.com/xijia-plus?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: wangsong
    password: XJspringbootplus@#

  ## 指定redis 配置文件
  redis:
    redisson:
      file: classpath:redisson-dev.yml

# 文件配置
# 默认支持： ALI_YUN_OSS -阿里云oss | LOCAL -本地服务器存储
file:
  ## 文件存储渠道
  channel: ALI_YUN_OSS
  ## 本地服务器存储：本地文件存储的根目录 | 文件访问地址
  local:
    path: upload
    baseUrl: http://127.0.0.1:9048
  ## 阿里云oss文件存储
  aliyun-oss:
    path: oss/file/
    ## 对象存储服务，个人账号,拉取此代码调试后请修改为自己的,如发现滥用,将关停
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    bucketName: xijia-sz
    bucket: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com

# 日志配置,日志存放地址(logback-spring.xml 读取), methods 记录那些请求持久化到数据到数据库
logging:
  filePath: logs
  methods: POST,PUT,DELETE
