server:
  port: 9049

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbkpoec225c821d8vo.mysql.zhangbei.rds.aliyuncs.com/xijia-plus?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: wangsong
    password: XJspringbootplus@#
  redis:
    redisson:
      file: classpath:redisson-pro.yml

file:
  # 渠道: 阿里云【ALI_YUN_OSS】 | 本地【LOCAL】
  channel: ALI_YUN_OSS
  local:
    path: File/upload
    baseUrl: http://127.0.0.1:9048
  # 如果使用 ALI_YUN_OSS 渠道, 下方配置请使用自己的阿里云 oss 地址
  aliyun-oss:
    path: oss/file/
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    bucketName: xijia-sz
    bucket: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com

logging:
  filePath: /data/logs
  methods: POST,PUT,DELETE

swagger:
  packages:
    - "架构--系统功能-管理端 | io.github.wslxm.springbootplus2.manage"
    - "架构--系统功能-用户端 | io.github.wslxm.springbootplus2.client"
    - "架构--通用服务-starter | io.github.wslxm.springbootplus2.starter"
    - "架构--文件管理 | io.github.wslxm.springbootplus2.file"
  author: wangsong
  email: 1270696548@qq.com
  url: https://gitee.com/wslxm/spring-boot-plus2
  termsOfServiceUrl:
  version: 2.0.0
  defaultKey: TOKEN | Authorization
  defaultValue: token | token
  isShow: true
