server:
  port: 7002

wechat:
  open:
    ## 回调地址-页面
    callbackUrl: https://portal.clzytech.com/portal/loginback?method=weichat
    ## 自己的appID和appKey
    appId: wxa6778e201b26f0c0
    appSecret: 5624eae2bca46202493bfb1edd41d5b2

# swagger配置
swagger:
  ## (模块名称 | 扫包路径),最多可配置10个
  #packages:
  #  - "通用模块 | io.github.wslxm.modules.third"
  # author: wangsong                                 # 作者/负责人-姓名
  # email: 1270696548@qq.com                         # 作者/负责人-邮箱
  # url: https://gitee.com/wslxm/spring-boot-plus2   # 作者/负责人-个人社交地址
  # termsOfServiceUrl:                               # 服务条款-访问地址
  # version: 1.0.1                                   # 版本号
  # defaultKey: TOKEN                                # 默认请求头key
  # defaultValue: token                              # 默认请求头值-当为token时，可以访问任意接口, 但接口中存在获取token用户信息时,将返回jwt解析错误
  # isShow: true                                     # 是否开启文档 true展示 false隐藏

