## 服务
server:
  port: 10001

spring:
  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 1024MB      # 单个文件的最大上限
      max-request-size: 1024MB   # 单个请求的文件总大小上限

# 文件配置
# 默认支持： ALI_YUN_OSS -阿里云oss | LOCAL -本地服务器存储
file:
  ## 文件存储渠道
  channel: ALI_YUN_OSS
  ## 本地服务器存储：本地文件存储的根目录 | 文件访问地址
  local:
    path: upload/file
    baseUrl: http://127.0.0.1:10001
  ## 阿里云oss文件存储
  aliyun-oss:
    path: oss/file/
    ## 对象存储服务，个人账号,拉取此代码调试后请修改为自己的,如发现滥用,将关停
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    bucketName: xijia-sz
    bucket: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com


# swagger配置
swagger:
  ## (模块名称 | 扫包路径),最多可配置10个
  packages:
    - "架构--文件管理 | io.github.wslxm.springbootplus2.file"
  author: wangsong                                 # 作者/负责人-姓名
  email: 1270696548@qq.com                         # 作者/负责人-邮箱
  url: https://gitee.com/wslxm/spring-boot-plus2   # 作者/负责人-个人社交地址
  termsOfServiceUrl:                               # 服务条款-访问地址
  version: 2.0.0                                   # 版本号
  defaultKey: TOKEN | Authorization                # 默认请求头key
  defaultValue: token | token                      # 默认请求头值-当为token时，可以访问任意接口, 但接口中存在获取token用户信息时,将返回jwt解析错误
  isShow: true                                     # 是否开启文档 true展示 false隐藏
